### ISSUE TITLE
Uncaught TypeError: Cannot read property 'getLastBufferRow' of undefined

### ISSUE THREAD

**Issue by YarnSphere** [robballou/atom-fold-functions#11]
I came across this bug because I have a button in my tool bar for the folding/unfolding actions (which I accidentally pressed when no file was open). :smiley:

Keep up the good work!
### Steps to Reproduce
1. Attempt folding/unfolding when no file is being shown.

**Atom Version**: 1.2.1
**System**: linux 4.2.5-1-ARCH
**Thrown From**: [fold-functions](https://github.com/robballou/atom-fold-functions) package, v0.4.3
### Stack Trace

Uncaught TypeError: Cannot read property 'getLastBufferRow' of undefined

```
At /home/nunomartins/.atom/packages/fold-functions/lib/fold-functions.coffee:66

TypeError: Cannot read property 'getLastBufferRow' of undefined
    at Object.module.exports.AtomFoldFunctions.fold (/home/nunomartins/.atom/packages/fold-functions/lib/fold-functions.coffee:66:16)
    at atom-workspace.subscriptions.add.atom.commands.add.fold-functions:fold (/home/nunomartins/.atom/packages/fold-functions/lib/fold-functions.coffee:32:34)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:260:29)
    at /usr/share/atom/resources/app.asar/src/command-registry.js:3:61
    at CommandPaletteView.module.exports.CommandPaletteView.confirmed (/usr/share/atom/resources/app.asar/node_modules/command-palette/lib/command-palette-view.js:159:32)
    at CommandPaletteView.module.exports.SelectListView.confirmSelection (/usr/share/atom/resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:338:21)
    at space-pen-div.atom.commands.add.core:confirm (/usr/share/atom/resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:109:19)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:260:29)
    at /usr/share/atom/resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:533:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:356:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeydown (/usr/share/atom/resources/app.asar/src/window-event-handler.js:99:36)
    at HTMLDocument.<anonymous> (/usr/share/atom/resources/app.asar/src/window-event-handler.js:3:61)
```

**Comment by robballou** [comment]
That's a great find! I have added a couple commits (not in a release yet) that should address it. Try it out.
